name: talemwa
description: Talemwa — Ministry App by Pastor Robert Talemwa
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Audio
  just_audio: ^0.9.36
  audio_service: ^0.18.12

  # Video / YouTube
  youtube_player_flutter: ^8.1.2

  # HTTP & Storage
  dio: ^5.4.0
  hive_flutter: ^1.1.0

  # State
  flutter_riverpod: ^2.4.9

  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9

  # UI
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  timeago: ^3.6.1

  # Navigation
  go_router: ^13.0.0

  # WebView (Flutterwave checkout)
  webview_flutter: ^4.4.2

  # Utils
  url_launcher: ^6.2.4
  share_plus: ^7.2.1
  intl: ^0.18.1
  package_info_plus: ^5.0.1
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
